# Site settings
title: Rabbit_TJ Blog
SEOTitle: 汤键的博客 | Rabbit_TJ Blog
header-img: "https://pic.imgdb.cn/item/65d09b529f345e8d03336410.jpg"
email: 1820291307@aliyun.com
description: "All is but a retracing and reconstruction."
keyword: "兔子队列, Rabbit_TJ Blog, 汤键的博客, 1820291307, 汤键, Apache, Java, Spring"
url: "https://CGITJ.github.io"          # my host, for absolute URL
baseurl: ""
github_repo: "https://github.com/CGITJ/CGITJ.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "站点统计<br>文章数：8篇<br>总字数：19620"
sidebar-avatar: https://pic.imgdb.cn/item/65d09b519f345e8d0333605e.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     apachetj
github_username:    CGITJ
facebook_username:  2131289595721031
jianshu_username:   weixin_59624686




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: CGITJ.github.io    #仓库名称
  owner: CGITJ    #github用户名
  admin: CGITJ
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apache",
        href: "https://www.apache.org/"
    },{
        title: "Oracle",
        href: "https://www.oracle.com/"
    },{
        title: "Spring",
        href: "https://spring.io/"
    },{
        title: "Google",
        href: "https://about.google/"
    }
]
